import os
import json
import hashlib
from datetime import datetime, timezone
from pathlib import Path
from sqlmodel import Session, select
from .models import CVE, IoC
from .database import engine

OUTPUT_DIR = Path(os.getenv("OUTPUT_DIR", "output_rules"))
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)


# ─── Snort / Suricata ─────────────────────────────────────────────────────────

def _snort_ip_rule(ioc: IoC, cve: CVE) -> str:
    """Generate a Snort/Suricata drop rule for a malicious IPv4 indicator."""
    score = cve.cvss_v3_score or 0
    severity = "1" if score >= 9 else "2" if score >= 7 else "3"
    msg = f"Malicious IP associated with {ioc.cve_id}"
    if ioc.pulse_name:
        msg += f" [{ioc.pulse_name[:40]}]"
        
    sid = int(hashlib.md5(ioc.value.encode()).hexdigest(), 16) % 9999999
    
    return (
        f'drop ip {ioc.value} any -> $HOME_NET any '
        f'(msg:"{msg}"; '
        f'reference:url,nvd.nist.gov/vuln/detail/{ioc.cve_id}; '
        f'classtype:trojan-activity; sid:{sid}; '
        f'priority:{severity}; rev:1;)'
    )


def generate_snort_rules() -> str:
    """Generate Snort/Suricata rules from all IPv4/IPv6 IoCs in the DB."""
    from sqlalchemy import text

    with Session(engine) as session:
        query = text("""
            SELECT i.value, i.ioc_type, i.pulse_name,
                   c.cve_id, c.cvss_v3_score
            FROM ioc i
            JOIN cve c ON c.cve_id = i.cve_id
            WHERE i.ioc_type IN ('IPv4', 'IPv6')
            ORDER BY c.cvss_v3_score DESC, c.cve_id ASC
        """)
        rows = session.exec(query).fetchall()

    lines = [
        f"# ═══════════════════════════════════════════════════════════",
        f"# VulnForge – Precision Threat Intelligence Platform",
        f"# Made by Darshak Patel",
        f"# [dp-watermark-2026]",
        f"# ═══════════════════════════════════════════════════════════",
        f"# Snort/Suricata rules generated by Vulnerability Tracker",
        f"# Generated at: {datetime.now(timezone.utc).isoformat()}",
        f"# Total rules: {len(rows)}",
        f"# DISCLAMER: Use at your own risk. Attribution required.",
        "",
    ]

    current_cve = None

    for row in rows:
        ip         = row[0]   # i.value
        cve_id     = row[3]   # c.cve_id
        
        if cve_id != current_cve:
            if current_cve is not None:
                lines.append("")
            lines.append(f"# {'='*76}")
            lines.append(f"# {cve_id}")
            lines.append(f"# {'='*76}")
            current_cve = cve_id

        score      = row[4] or 0
        pulse_name = (row[2] or "")[:40]
        priority   = "1" if score >= 9 else "2" if score >= 7 else "3"
        sid        = int(hashlib.md5(ip.encode()).hexdigest(), 16) % 9999999
        msg        = f"Malicious IP associated with {cve_id}"
        if pulse_name:
            msg += f" [{pulse_name}]"

        rule = (
            f'drop ip {ip} any -> $HOME_NET any '
            f'(msg:"{msg}"; '
            f'reference:url,nvd.nist.gov/vuln/detail/{cve_id}; '
            f'classtype:trojan-activity; sid:{sid}; '
            f'priority:{priority}; rev:1;)'
        )
        lines.append(rule)

    if not rows:
        lines.append("# No IPv4/IPv6 IoCs available yet. Run a fetch to populate rules.")

    content = "\n".join(lines)
    (OUTPUT_DIR / "snort.rules").write_text(content, encoding="utf-8")
    return content


# ─── Sigma ────────────────────────────────────────────────────────────────────

def generate_sigma_rules() -> str:
    """Generate Sigma YAML rules for high-severity CVEs flagged as KEV."""
    import yaml

    rules = []
    with Session(engine) as session:
        kev_cves = session.exec(
            select(CVE).where(CVE.is_kev == True).order_by(CVE.cvss_v3_score.desc()).limit(100)
        ).all()

        for cve in kev_cves:
            rule = {
                "title": f"Exploitation attempt for {cve.cve_id}",
                "id": f"vuln-tracker-{cve.cve_id.lower().replace('-', '_')}",
                "status": "experimental",
                "description": (cve.description or "")[:300],
                "references": [f"https://nvd.nist.gov/vuln/detail/{cve.cve_id}"],
                "tags": [f"attack.initial_access", f"cve.{cve.cve_id.lower()}"],
                "logsource": {"category": "network", "product": "firewall"},
                "detection": {
                    "keywords": [cve.cve_id],
                    "condition": "keywords"
                },
                "level": "critical" if (cve.cvss_v3_score or 0) >= 9 else "high",
            }
            rules.append(rule)

    if rules:
        content = "\n---\n".join(
            f"# Sigma rule for {r['id']}\n" + json.dumps(r, indent=2) for r in rules
        )
    else:
        content = "# No CISA KEV CVEs available yet. Run a fetch to populate rules."

    full_content = (
        f"# ═══════════════════════════════════════════════════════════\n"
        f"# VulnForge – Precision Threat Intelligence Platform\n"
        f"# Made by Darshak Patel\n"
        f"# [dp-watermark-2026]\n"
        f"# ═══════════════════════════════════════════════════════════\n"
        f"# Sigma rules generated by Vulnerability Tracker\n"
        f"# Generated at: {datetime.now(timezone.utc).isoformat()}\n\n"
        + content
    )
    (OUTPUT_DIR / "sigma.yml").write_text(full_content, encoding="utf-8")
    return full_content


# ─── Generic JSON ─────────────────────────────────────────────────────────────

def generate_json_alerts() -> str:
    """Generate a JSON alert feed for the top CVEs (CRITICAL + KEV)."""
    alerts = []

    with Session(engine) as session:
        cves = session.exec(
            select(CVE)
            .where(CVE.cvss_v3_score >= 7)
            .order_by(CVE.cvss_v3_score.desc())
            .limit(200)
        ).all()

        for cve in cves:
            # Gather IoCs for this CVE
            iocs = session.exec(select(IoC).where(IoC.cve_id == cve.cve_id)).all()
            alerts.append({
                "cve_id": cve.cve_id,
                "severity": cve.cvss_v3_severity,
                "cvss_score": cve.cvss_v3_score,
                "is_kev": cve.is_kev,
                "description": cve.description[:300] if cve.description else "",
                "published": cve.published.isoformat() if cve.published else None,
                "ioc_count": len(iocs),
                "iocs": [{"type": i.ioc_type, "value": i.value} for i in iocs[:10]],
                "nvd_url": f"https://nvd.nist.gov/vuln/detail/{cve.cve_id}",
                "generated_at": datetime.now(timezone.utc).isoformat(),
            })

    if not alerts:
        alerts = [{"message": "No CVEs available yet. Run a fetch to populate alerts."}]

    content_dict = {
        "metadata": {
            "title": "VulnForge Alert Feed",
            "made_by": "Darshak Patel",
            "watermark": "[dp-watermark-2026]",
            "generated_at": datetime.now(timezone.utc).isoformat(),
        },
        "alerts": alerts,
        "count": len(alerts)
    }
    content = json.dumps(content_dict, indent=2)
    (OUTPUT_DIR / "alerts.json").write_text(content, encoding="utf-8")
    return content


# ─── Master Generator ─────────────────────────────────────────────────────────

def generate_all_rules() -> dict:
    """Generate all rule types and return a summary."""
    snort = generate_snort_rules()
    sigma = generate_sigma_rules()
    json_alerts = generate_json_alerts()
    return {
        "snort_rules_lines": snort.count("\n"),
        "sigma_rules_lines": sigma.count("\n"),
        "json_alerts_bytes": len(json_alerts),
        "output_dir": str(OUTPUT_DIR.resolve()),
    }
